# coding: utf-8

"""
    Webhook Event Receiver API

    This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\". 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.commissioning_data import CommissioningData  # noqa: E501

class TestCommissioningData(unittest.TestCase):
    """CommissioningData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommissioningData:
        """Test CommissioningData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommissioningData`
        """
        model = CommissioningData()  # noqa: E501
        if include_optional:
            return CommissioningData(
                customer_id = '1a81c4f4-5f6c-48e6-be91-2528c1c0bb28',
                customer_email = 'test@email.com',
                customer_address = 'Straße Str. 1, 20359, Hamburg, Germany',
                system_name = 'Test system',
                gateway_serialnumber = 'D403-007-000-000-001-B-X'
            )
        else:
            return CommissioningData(
        )
        """

    def testCommissioningData(self):
        """Test CommissioningData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
