# coding: utf-8

"""
    Webhook Event Receiver API

    This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\". 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.gateway_event_data import GatewayEventData  # noqa: E501

class TestGatewayEventData(unittest.TestCase):
    """GatewayEventData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GatewayEventData:
        """Test GatewayEventData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GatewayEventData`
        """
        model = GatewayEventData()  # noqa: E501
        if include_optional:
            return GatewayEventData(
                gateway_id = '680d63aa-6e1d-4447-af7c-35c5eb6ca810',
                gateway_name = 'My gridBox',
                gateway_serialnumber = 'D403-007-000-000-001-B-X',
                system_id = 'af87d7b3-316f-4d26-868c-4ae351095bdc',
                system_name = 'ExampleSystem',
                user_id = 'a115d9e3-6e78-4ddf-8676-a98c28ad8249',
                user_name = 'Max Mustermann',
                user_mail = 'max.mustermann@muster.de'
            )
        else:
            return GatewayEventData(
                gateway_id = '680d63aa-6e1d-4447-af7c-35c5eb6ca810',
                system_id = 'af87d7b3-316f-4d26-868c-4ae351095bdc',
        )
        """

    def testGatewayEventData(self):
        """Test GatewayEventData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
