# coding: utf-8

"""
    Webhook Event Receiver API

    This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\". 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.webhook_receiver_api import WebhookReceiverApi  # noqa: E501


class TestWebhookReceiverApi(unittest.TestCase):
    """WebhookReceiverApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhookReceiverApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_events_event_type_post(self) -> None:
        """Test case for events_event_type_post

        Webhook Receiver  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
