# coding: utf-8

"""
    Webhook Event Receiver API

    This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\". 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.event import Event  # noqa: E501

class TestEvent(unittest.TestCase):
    """Event unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Event:
        """Test Event
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Event`
        """
        model = Event()  # noqa: E501
        if include_optional:
            return Event(
                id = '',
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 'appliance/create',
                data_content_type = 'application/json',
                spec_version = '1.0',
                data = openapi_client.models.event_data.Event_data(),
                source = '/systems/5eda17ec-4dc9-46d5-b3b8-c396f75a760f',
                correlation_id = '',
                notification = {"recipient":{"accountID":"046b6c7f-0b8a-43b9-b35d-6489e6daee91","fullName":"fullName","locale":"fr_FR","userID":"046b6c7f-0b8a-43b9-b35d-6489e6daee91","email":"email"},"message":{"textContentType":"text/html","actionURL":"http://example.com/aeiou","text":"text","title":""}}
            )
        else:
            return Event(
                id = '',
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 'appliance/create',
                spec_version = '1.0',
                source = '/systems/5eda17ec-4dc9-46d5-b3b8-c396f75a760f',
        )
        """

    def testEvent(self):
        """Test Event"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
