# coding: utf-8

"""
    Webhook Event Receiver API

    This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\". 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.event_data import EventData  # noqa: E501

class TestEventData(unittest.TestCase):
    """EventData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventData:
        """Test EventData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventData`
        """
        model = EventData()  # noqa: E501
        if include_optional:
            return EventData(
                appliance_id = 'fc0a6ac7-64ce-4276-a7cd-bace946af433',
                gateway_id = '25ccab17-cd40-4db1-a320-a986d1c15fb1',
                model = 'Baz',
                manufacturer = 'Iskraemeco',
                type = 'METER',
                kind = 'BATTERY',
                name = 'ExampleMeter',
                serial_number = '9312355',
                system_id = 'c9db369e-7cf8-4ad1-ade5-46f61a5125c2',
                system_name = 'Test system',
                status = 'OK',
                last_status = 'ERROR',
                err_code = '',
                last_err_code = 'F71A',
                gateway_name = 'My gridBox',
                gateway_serialnumber = 'D403-007-000-000-001-B-X',
                user_id = 'a115d9e3-6e78-4ddf-8676-a98c28ad8249',
                user_name = 'Max Mustermann',
                user_mail = 'max.mustermann@muster.de',
                evse_id = 'FR*A23*E45B*78C',
                state = 'plugged',
                customer_id = '1a81c4f4-5f6c-48e6-be91-2528c1c0bb28',
                customer_email = 'test@email.com',
                customer_address = 'Straße Str. 1, 20359, Hamburg, Germany'
            )
        else:
            return EventData(
                appliance_id = 'fc0a6ac7-64ce-4276-a7cd-bace946af433',
                gateway_id = '25ccab17-cd40-4db1-a320-a986d1c15fb1',
                system_id = 'c9db369e-7cf8-4ad1-ade5-46f61a5125c2',
                status = 'OK',
                last_status = 'ERROR',
                state = 'plugged',
        )
        """

    def testEventData(self):
        """Test EventData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
