# coding: utf-8

"""
    Webhook Event Receiver API

    This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\". 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.notification_recipient import NotificationRecipient  # noqa: E501

class TestNotificationRecipient(unittest.TestCase):
    """NotificationRecipient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationRecipient:
        """Test NotificationRecipient
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationRecipient`
        """
        model = NotificationRecipient()  # noqa: E501
        if include_optional:
            return NotificationRecipient(
                user_id = '',
                account_id = '',
                email = '',
                full_name = '',
                locale = 'fr_FR'
            )
        else:
            return NotificationRecipient(
        )
        """

    def testNotificationRecipient(self):
        """Test NotificationRecipient"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
