# coding: utf-8

"""
    Webhook Event Receiver API

    This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\". 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class CommissioningData(BaseModel):
    """
    Payload for `commissioning/done` events.  # noqa: E501
    """
    customer_id: Optional[StrictStr] = Field(None, alias="customerID", description="The ID of the newly created customer after the commissioning process.")
    customer_email: Optional[StrictStr] = Field(None, alias="customerEmail", description="The email of the newly created customer after the commissioning process.")
    customer_address: Optional[StrictStr] = Field(None, alias="customerAddress", description="The address of the newly created customer after the commissioning process.")
    system_name: Optional[StrictStr] = Field(None, alias="systemName", description="The name of the commissioned system.")
    gateway_serialnumber: Optional[StrictStr] = Field(None, alias="gatewaySerialnumber", description="The serialnumber of the gateway corresponding to the commissioned system.")
    __properties = ["customerID", "customerEmail", "customerAddress", "systemName", "gatewaySerialnumber"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CommissioningData:
        """Create an instance of CommissioningData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CommissioningData:
        """Create an instance of CommissioningData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CommissioningData.parse_obj(obj)

        _obj = CommissioningData.parse_obj({
            "customer_id": obj.get("customerID"),
            "customer_email": obj.get("customerEmail"),
            "customer_address": obj.get("customerAddress"),
            "system_name": obj.get("systemName"),
            "gateway_serialnumber": obj.get("gatewaySerialnumber")
        })
        return _obj


