# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class ApplianceEventData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, appliance_id: str=None, gateway_id: str=None, model: str=None, manufacturer: str=None, type: str=None, kind: str=None, name: str=None, serial_number: str=None, system_id: str=None, system_name: str=None):
        """ApplianceEventData - a model defined in OpenAPI

        :param appliance_id: The appliance_id of this ApplianceEventData.
        :param gateway_id: The gateway_id of this ApplianceEventData.
        :param model: The model of this ApplianceEventData.
        :param manufacturer: The manufacturer of this ApplianceEventData.
        :param type: The type of this ApplianceEventData.
        :param kind: The kind of this ApplianceEventData.
        :param name: The name of this ApplianceEventData.
        :param serial_number: The serial_number of this ApplianceEventData.
        :param system_id: The system_id of this ApplianceEventData.
        :param system_name: The system_name of this ApplianceEventData.
        """
        self.openapi_types = {
            'appliance_id': str,
            'gateway_id': str,
            'model': str,
            'manufacturer': str,
            'type': str,
            'kind': str,
            'name': str,
            'serial_number': str,
            'system_id': str,
            'system_name': str
        }

        self.attribute_map = {
            'appliance_id': 'applianceID',
            'gateway_id': 'gatewayID',
            'model': 'model',
            'manufacturer': 'manufacturer',
            'type': 'type',
            'kind': 'kind',
            'name': 'name',
            'serial_number': 'serialNumber',
            'system_id': 'systemID',
            'system_name': 'systemName'
        }

        self._appliance_id = appliance_id
        self._gateway_id = gateway_id
        self._model = model
        self._manufacturer = manufacturer
        self._type = type
        self._kind = kind
        self._name = name
        self._serial_number = serial_number
        self._system_id = system_id
        self._system_name = system_name

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ApplianceEventData':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ApplianceEventData of this ApplianceEventData.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def appliance_id(self):
        """Gets the appliance_id of this ApplianceEventData.

        ID of the appliance that caused this event.

        :return: The appliance_id of this ApplianceEventData.
        :rtype: str
        """
        return self._appliance_id

    @appliance_id.setter
    def appliance_id(self, appliance_id):
        """Sets the appliance_id of this ApplianceEventData.

        ID of the appliance that caused this event.

        :param appliance_id: The appliance_id of this ApplianceEventData.
        :type appliance_id: str
        """
        if appliance_id is None:
            raise ValueError("Invalid value for `appliance_id`, must not be `None`")

        self._appliance_id = appliance_id

    @property
    def gateway_id(self):
        """Gets the gateway_id of this ApplianceEventData.

        The ID of the gateway that connects to the appliance.

        :return: The gateway_id of this ApplianceEventData.
        :rtype: str
        """
        return self._gateway_id

    @gateway_id.setter
    def gateway_id(self, gateway_id):
        """Sets the gateway_id of this ApplianceEventData.

        The ID of the gateway that connects to the appliance.

        :param gateway_id: The gateway_id of this ApplianceEventData.
        :type gateway_id: str
        """
        if gateway_id is None:
            raise ValueError("Invalid value for `gateway_id`, must not be `None`")

        self._gateway_id = gateway_id

    @property
    def model(self):
        """Gets the model of this ApplianceEventData.

        Model description of the appliance.

        :return: The model of this ApplianceEventData.
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this ApplianceEventData.

        Model description of the appliance.

        :param model: The model of this ApplianceEventData.
        :type model: str
        """

        self._model = model

    @property
    def manufacturer(self):
        """Gets the manufacturer of this ApplianceEventData.

        Manufacturer of the appliance.

        :return: The manufacturer of this ApplianceEventData.
        :rtype: str
        """
        return self._manufacturer

    @manufacturer.setter
    def manufacturer(self, manufacturer):
        """Sets the manufacturer of this ApplianceEventData.

        Manufacturer of the appliance.

        :param manufacturer: The manufacturer of this ApplianceEventData.
        :type manufacturer: str
        """

        self._manufacturer = manufacturer

    @property
    def type(self):
        """Gets the type of this ApplianceEventData.

        General type of the appliance.

        :return: The type of this ApplianceEventData.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ApplianceEventData.

        General type of the appliance.

        :param type: The type of this ApplianceEventData.
        :type type: str
        """
        allowed_values = ["UNKNOWN", "INVERTER", "METER", "EVSTATION", "HEAT_PUMP", "HEATER", "CONTAINER"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def kind(self):
        """Gets the kind of this ApplianceEventData.

        Kind of the appliance is used to provide further details on the appliance configuration and mode of operation. The kind property is only available for appliances with type INVERTER or METER. For inverters, only UNKNOWN, PV, BATTERY, HYBRID and PV_EXTERNAL are valid values. They describe the  kind of connected appliance(s) and define the role of the inverter in the system. For meters, kind specifies the appliance the meter is attached to. It resembles the location the meter is installed in. 

        :return: The kind of this ApplianceEventData.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this ApplianceEventData.

        Kind of the appliance is used to provide further details on the appliance configuration and mode of operation. The kind property is only available for appliances with type INVERTER or METER. For inverters, only UNKNOWN, PV, BATTERY, HYBRID and PV_EXTERNAL are valid values. They describe the  kind of connected appliance(s) and define the role of the inverter in the system. For meters, kind specifies the appliance the meter is attached to. It resembles the location the meter is installed in. 

        :param kind: The kind of this ApplianceEventData.
        :type kind: str
        """
        allowed_values = ["UNKNOWN", "PV", "BATTERY", "HYBRID", "PV_EXTERNAL", "GRID", "HEAT_PUMP", "FUEL_CELL", "HEAT_PUMP_EXTERNAL", "EVSTATION", "BTTP", "HEATING", "MISC", "CLUSTER", "WIND_TURBINE"]  # noqa: E501
        if kind not in allowed_values:
            raise ValueError(
                "Invalid value for `kind` ({0}), must be one of {1}"
                .format(kind, allowed_values)
            )

        self._kind = kind

    @property
    def name(self):
        """Gets the name of this ApplianceEventData.

        The name of the appliance as defined by the customer.

        :return: The name of this ApplianceEventData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApplianceEventData.

        The name of the appliance as defined by the customer.

        :param name: The name of this ApplianceEventData.
        :type name: str
        """

        self._name = name

    @property
    def serial_number(self):
        """Gets the serial_number of this ApplianceEventData.

        Serial number of the appliance as returned by the appliance.

        :return: The serial_number of this ApplianceEventData.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this ApplianceEventData.

        Serial number of the appliance as returned by the appliance.

        :param serial_number: The serial_number of this ApplianceEventData.
        :type serial_number: str
        """

        self._serial_number = serial_number

    @property
    def system_id(self):
        """Gets the system_id of this ApplianceEventData.

        The ID of the system that the gateway and appliance run in.

        :return: The system_id of this ApplianceEventData.
        :rtype: str
        """
        return self._system_id

    @system_id.setter
    def system_id(self, system_id):
        """Sets the system_id of this ApplianceEventData.

        The ID of the system that the gateway and appliance run in.

        :param system_id: The system_id of this ApplianceEventData.
        :type system_id: str
        """
        if system_id is None:
            raise ValueError("Invalid value for `system_id`, must not be `None`")

        self._system_id = system_id

    @property
    def system_name(self):
        """Gets the system_name of this ApplianceEventData.

        Name of the system as defined by the customer.

        :return: The system_name of this ApplianceEventData.
        :rtype: str
        """
        return self._system_name

    @system_name.setter
    def system_name(self, system_name):
        """Sets the system_name of this ApplianceEventData.

        Name of the system as defined by the customer.

        :param system_name: The system_name of this ApplianceEventData.
        :type system_name: str
        """

        self._system_name = system_name
