# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class GatewayEventData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, gateway_id: str=None, gateway_name: str=None, gateway_serialnumber: str=None, system_id: str=None, system_name: str=None, user_id: str=None, user_name: str=None, user_mail: str=None):
        """GatewayEventData - a model defined in OpenAPI

        :param gateway_id: The gateway_id of this GatewayEventData.
        :param gateway_name: The gateway_name of this GatewayEventData.
        :param gateway_serialnumber: The gateway_serialnumber of this GatewayEventData.
        :param system_id: The system_id of this GatewayEventData.
        :param system_name: The system_name of this GatewayEventData.
        :param user_id: The user_id of this GatewayEventData.
        :param user_name: The user_name of this GatewayEventData.
        :param user_mail: The user_mail of this GatewayEventData.
        """
        self.openapi_types = {
            'gateway_id': str,
            'gateway_name': str,
            'gateway_serialnumber': str,
            'system_id': str,
            'system_name': str,
            'user_id': str,
            'user_name': str,
            'user_mail': str
        }

        self.attribute_map = {
            'gateway_id': 'gatewayID',
            'gateway_name': 'gatewayName',
            'gateway_serialnumber': 'gatewaySerialnumber',
            'system_id': 'systemID',
            'system_name': 'systemName',
            'user_id': 'userID',
            'user_name': 'userName',
            'user_mail': 'userMail'
        }

        self._gateway_id = gateway_id
        self._gateway_name = gateway_name
        self._gateway_serialnumber = gateway_serialnumber
        self._system_id = system_id
        self._system_name = system_name
        self._user_id = user_id
        self._user_name = user_name
        self._user_mail = user_mail

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GatewayEventData':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GatewayEventData of this GatewayEventData.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def gateway_id(self):
        """Gets the gateway_id of this GatewayEventData.

        The ID of the gateway this event is triggered for.

        :return: The gateway_id of this GatewayEventData.
        :rtype: str
        """
        return self._gateway_id

    @gateway_id.setter
    def gateway_id(self, gateway_id):
        """Sets the gateway_id of this GatewayEventData.

        The ID of the gateway this event is triggered for.

        :param gateway_id: The gateway_id of this GatewayEventData.
        :type gateway_id: str
        """
        if gateway_id is None:
            raise ValueError("Invalid value for `gateway_id`, must not be `None`")

        self._gateway_id = gateway_id

    @property
    def gateway_name(self):
        """Gets the gateway_name of this GatewayEventData.

        The name of the gateway corresponding to the gatewayID.

        :return: The gateway_name of this GatewayEventData.
        :rtype: str
        """
        return self._gateway_name

    @gateway_name.setter
    def gateway_name(self, gateway_name):
        """Sets the gateway_name of this GatewayEventData.

        The name of the gateway corresponding to the gatewayID.

        :param gateway_name: The gateway_name of this GatewayEventData.
        :type gateway_name: str
        """

        self._gateway_name = gateway_name

    @property
    def gateway_serialnumber(self):
        """Gets the gateway_serialnumber of this GatewayEventData.

        The serialnumber of the gateway corresponding to the gatewayID.

        :return: The gateway_serialnumber of this GatewayEventData.
        :rtype: str
        """
        return self._gateway_serialnumber

    @gateway_serialnumber.setter
    def gateway_serialnumber(self, gateway_serialnumber):
        """Sets the gateway_serialnumber of this GatewayEventData.

        The serialnumber of the gateway corresponding to the gatewayID.

        :param gateway_serialnumber: The gateway_serialnumber of this GatewayEventData.
        :type gateway_serialnumber: str
        """

        self._gateway_serialnumber = gateway_serialnumber

    @property
    def system_id(self):
        """Gets the system_id of this GatewayEventData.

        The ID of the system this event is triggered for.

        :return: The system_id of this GatewayEventData.
        :rtype: str
        """
        return self._system_id

    @system_id.setter
    def system_id(self, system_id):
        """Sets the system_id of this GatewayEventData.

        The ID of the system this event is triggered for.

        :param system_id: The system_id of this GatewayEventData.
        :type system_id: str
        """
        if system_id is None:
            raise ValueError("Invalid value for `system_id`, must not be `None`")

        self._system_id = system_id

    @property
    def system_name(self):
        """Gets the system_name of this GatewayEventData.

        The name of the system corresponding to the systemID.

        :return: The system_name of this GatewayEventData.
        :rtype: str
        """
        return self._system_name

    @system_name.setter
    def system_name(self, system_name):
        """Sets the system_name of this GatewayEventData.

        The name of the system corresponding to the systemID.

        :param system_name: The system_name of this GatewayEventData.
        :type system_name: str
        """

        self._system_name = system_name

    @property
    def user_id(self):
        """Gets the user_id of this GatewayEventData.

        The ID of the user that owns the system.

        :return: The user_id of this GatewayEventData.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this GatewayEventData.

        The ID of the user that owns the system.

        :param user_id: The user_id of this GatewayEventData.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def user_name(self):
        """Gets the user_name of this GatewayEventData.

        Name of the user belonging to the userID.

        :return: The user_name of this GatewayEventData.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this GatewayEventData.

        Name of the user belonging to the userID.

        :param user_name: The user_name of this GatewayEventData.
        :type user_name: str
        """

        self._user_name = user_name

    @property
    def user_mail(self):
        """Gets the user_mail of this GatewayEventData.

        E-Mail address of the user belonging to the userID.

        :return: The user_mail of this GatewayEventData.
        :rtype: str
        """
        return self._user_mail

    @user_mail.setter
    def user_mail(self, user_mail):
        """Sets the user_mail of this GatewayEventData.

        E-Mail address of the user belonging to the userID.

        :param user_mail: The user_mail of this GatewayEventData.
        :type user_mail: str
        """

        self._user_mail = user_mail
