/*
 * Webhook Event Receiver API
 *
 * This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\". 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Notification - Consists of a message and a recipient. Can be used by consumers to produce a notification `message` which can be sent to the `recipient`.
type Notification struct {

	Recipient NotificationRecipient `json:"recipient"`

	Message NotificationMessage `json:"message"`
}

// AssertNotificationRequired checks if the required fields are not zero-ed
func AssertNotificationRequired(obj Notification) error {
	elements := map[string]interface{}{
		"recipient": obj.Recipient,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNotificationRecipientRequired(obj.Recipient); err != nil {
		return err
	}
	if err := AssertNotificationMessageRequired(obj.Message); err != nil {
		return err
	}
	return nil
}

// AssertNotificationConstraints checks if the values respects the defined constraints
func AssertNotificationConstraints(obj Notification) error {
	return nil
}
