/*
 * Webhook Event Receiver API
 *
 * This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\". 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type NotificationMessage struct {

	// Title of the message, in the `locale` of the `recipient`. Subject to changes at any time.
	Title *interface{} `json:"title,omitempty"`

	// Content-Type of the `text` attribute.
	TextContentType string `json:"textContentType,omitempty"`

	// Exemplary text message in the `locale` of the `recipient`. Subject to changes at any time.
	Text string `json:"text,omitempty"`

	// URL that links to further information about the event's origin, usable for call-to-action buttons.
	ActionURL string `json:"actionURL,omitempty"`
}

// AssertNotificationMessageRequired checks if the required fields are not zero-ed
func AssertNotificationMessageRequired(obj NotificationMessage) error {
	return nil
}

// AssertNotificationMessageConstraints checks if the values respects the defined constraints
func AssertNotificationMessageConstraints(obj NotificationMessage) error {
	return nil
}
