// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example XENON webhook receiver
 *
 * This is an example webhook receiver for XENON.
 *
 * API version: v1.0.0
 * Contact: developer-community@gridx.de
 */

package openapi


import (
	"time"
)



type EvMeasurementEventData struct {

	// This field defines the id of the system in which the EV is connected to.
	SystemID string `json:"systemID"`

	// This field defines the id of the asset.
	AssetID string `json:"assetID"`

	// This field defines the ID of gateway where the EV is linked to.
	GatewayID string `json:"gatewayID"`

	// When the event was issued by the EV (It might take some time for the event reach us).
	IssuedAt time.Time `json:"issuedAt"`

	// atHome specifies if the vehicle is currently at the users home location and is used to make decisions on whether to control charging behaviour
	AtHome bool `json:"atHome"`

	// StateOfCharge specifies the vehicles battery level in as a value between 0.0% and 100.0%.
	StateOfCharge float32 `json:"stateOfCharge,omitempty"`

	// ChargePower specifies the power with which the vehicle is currently charging in mW Positive values mean charging, negative values mean discharging (V2G, V2H).
	ChargePower int64 `json:"chargePower"`

	// Range of the vehicle in meters
	Range int32 `json:"range,omitempty"`

	// ChargeLimit is the limit configured by the vehicle owner at which state of charge the vehicle should stop charging. Represented as a percentage between 0% and 100%.
	ChargeLimit float64 `json:"chargeLimit,omitempty"`

	// Capacity specifies the capacity of the vehicles battery in Wh.
	Capacity int32 `json:"capacity,omitempty"`
}

// AssertEvMeasurementEventDataRequired checks if the required fields are not zero-ed
func AssertEvMeasurementEventDataRequired(obj EvMeasurementEventData) error {
	elements := map[string]interface{}{
		"systemID": obj.SystemID,
		"assetID": obj.AssetID,
		"gatewayID": obj.GatewayID,
		"issuedAt": obj.IssuedAt,
		"atHome": obj.AtHome,
		"chargePower": obj.ChargePower,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEvMeasurementEventDataConstraints checks if the values respects the defined constraints
func AssertEvMeasurementEventDataConstraints(obj EvMeasurementEventData) error {
	return nil
}
