// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example XENON webhook receiver
 *
 * This is an example webhook receiver for XENON.
 *
 * API version: v1.0.0
 * Contact: developer-community@gridx.de
 */

package openapi




// PingEventData - Payload for `ping` events.
type PingEventData struct {

	Message string `json:"message,omitempty"`
}

// AssertPingEventDataRequired checks if the required fields are not zero-ed
func AssertPingEventDataRequired(obj PingEventData) error {
	return nil
}

// AssertPingEventDataConstraints checks if the values respects the defined constraints
func AssertPingEventDataConstraints(obj PingEventData) error {
	return nil
}
