/*
 * gridX Webhook Event Receiver API
 *
 * This API describes the event webhook calling convention. In order to receive webhook events from the gridX API, third parties must implement endpoints according to this specification. In the following, the external partner API is referred to as  \"external API\", while the gridX API is called \"gridX\".
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CommissioningData - Payload for `commissioning/done` events.
type CommissioningData struct {

	// The ID of the newly created customer after the commissioning process.
	CustomerID string `json:"customerID,omitempty"`

	// The email of the newly created customer after the commissioning process.
	CustomerEmail string `json:"customerEmail,omitempty"`

	// The address of the newly created customer after the commissioning process.
	CustomerAddress string `json:"customerAddress,omitempty"`

	// The name of the commissioned system.
	SystemName string `json:"systemName,omitempty"`

	// The serialnumber of the gateway corresponding to the commissioned system.
	GatewaySerialnumber string `json:"gatewaySerialnumber,omitempty"`
}

// AssertCommissioningDataRequired checks if the required fields are not zero-ed
func AssertCommissioningDataRequired(obj CommissioningData) error {
	return nil
}

// AssertCommissioningDataConstraints checks if the values respects the defined constraints
func AssertCommissioningDataConstraints(obj CommissioningData) error {
	return nil
}
