// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example XENON webhook receiver
 *
 * This is an example webhook receiver for XENON.
 *
 * API version: v1.0.0
 * Contact: developer-community@gridx.de
 */

package openapi




type SystemActionEventDataResolution struct {

	// A localized description of how to solve. Formatted as Markdown.
	Description string `json:"description"`

	// A localized title for the user action.
	Title string `json:"title"`

	// Where the action needs to be taken. i.e. remotely using the vendor's app or directly in the vehicle.
	Access string `json:"access"`

	// Who can resolve the action. i.e. a user can resolve themselves, or a licensed service retailer is needed.
	Agent string `json:"agent"`
}

// AssertSystemActionEventDataResolutionRequired checks if the required fields are not zero-ed
func AssertSystemActionEventDataResolutionRequired(obj SystemActionEventDataResolution) error {
	elements := map[string]interface{}{
		"description": obj.Description,
		"title": obj.Title,
		"access": obj.Access,
		"agent": obj.Agent,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSystemActionEventDataResolutionConstraints checks if the values respects the defined constraints
func AssertSystemActionEventDataResolutionConstraints(obj SystemActionEventDataResolution) error {
	return nil
}
