// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example XENON webhook receiver
 *
 * This is an example webhook receiver for XENON.
 *
 * API version: v1.0.0
 * Contact: developer-community@gridx.de
 */

package openapi


import (
	"time"
)



type EvChargeSessionEventData struct {

	// This field defines the id of the system in which the EV is connected to.
	SystemID string `json:"systemID"`

	// This field defines the id of the asset.
	AssetID string `json:"assetID"`

	// This field defines the ID of gateway where the EV is linked to.
	GatewayID string `json:"gatewayID"`

	// When the event was issued by the EV (It might take some time for the event reach us).
	IssuedAt time.Time `json:"issuedAt"`

	// atHome specifies if the vehicle is currently at the users home location and is used to make decisions on whether to control charging behaviour
	AtHome bool `json:"atHome"`

	// ChargeState defines whether the vehicle is charging
	State string `json:"state"`
}

// AssertEvChargeSessionEventDataRequired checks if the required fields are not zero-ed
func AssertEvChargeSessionEventDataRequired(obj EvChargeSessionEventData) error {
	elements := map[string]interface{}{
		"systemID": obj.SystemID,
		"assetID": obj.AssetID,
		"gatewayID": obj.GatewayID,
		"issuedAt": obj.IssuedAt,
		"atHome": obj.AtHome,
		"state": obj.State,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEvChargeSessionEventDataConstraints checks if the values respects the defined constraints
func AssertEvChargeSessionEventDataConstraints(obj EvChargeSessionEventData) error {
	return nil
}
