// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example XENON webhook receiver
 *
 * This is an example webhook receiver for XENON.
 *
 * API version: v1.0.0
 * Contact: developer-community@gridx.de
 */

package openapi




// EvEventDataBase - Generic EVEvent.
type EvEventDataBase struct {

	// This field defines the id of the system in which the EV is connected to.
	SystemID string `json:"systemID"`

	// This field defines the id of the asset.
	AssetID string `json:"assetID"`

	// This field defines the ID of gateway where the EV is linked to.
	GatewayID string `json:"gatewayID"`
}

// AssertEvEventDataBaseRequired checks if the required fields are not zero-ed
func AssertEvEventDataBaseRequired(obj EvEventDataBase) error {
	elements := map[string]interface{}{
		"systemID": obj.SystemID,
		"assetID": obj.AssetID,
		"gatewayID": obj.GatewayID,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEvEventDataBaseConstraints checks if the values respects the defined constraints
func AssertEvEventDataBaseConstraints(obj EvEventDataBase) error {
	return nil
}
