// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example XENON webhook receiver
 *
 * This is an example webhook receiver for XENON.
 *
 * API version: v1.0.0
 * Contact: developer-community@gridx.de
 */

package openapi


import (
	"time"
)



// Gsp14aSignalEventData - Payload for `grid-signal-processor/limitation-of-power-consumption/_*` events.
type Gsp14aSignalEventData struct {

	// Represents the new limitation of power consumption in milliwatt. It can be omitted in case there was a limit  and now there is not.
	NewLPC float32 `json:"newLPC,omitempty"`

	// Timestamp at which the gridbox received the control signal.
	ReceivedAt time.Time `json:"receivedAt,omitempty"`

	// Timestamp until which the control signal is valid.
	ValidUntil time.Time `json:"validUntil,omitempty"`
}

// AssertGsp14aSignalEventDataRequired checks if the required fields are not zero-ed
func AssertGsp14aSignalEventDataRequired(obj Gsp14aSignalEventData) error {
	return nil
}

// AssertGsp14aSignalEventDataConstraints checks if the values respects the defined constraints
func AssertGsp14aSignalEventDataConstraints(obj Gsp14aSignalEventData) error {
	return nil
}
