// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Example XENON webhook receiver
 *
 * This is an example webhook receiver for XENON.
 *
 * API version: v1.0.0
 * Contact: developer-community@gridx.de
 */

package openapi


import (
	"time"
)



type SystemActionEventData struct {

	// ID of the action.
	Id string `json:"id"`

	// Type of asset.
	Type string `json:"type"`

	// Manufacturer of the asset.
	Manufacturer string `json:"manufacturer"`

	// Describes whether the user action relates to the device itself or the vendor user account used to access the device.
	Domain string `json:"domain"`

	// ISO8601 UTC timestamp of when the user action was introduced.
	IntroducedAt time.Time `json:"introducedAt"`

	Resolution SystemActionEventDataResolution `json:"resolution"`
}

// AssertSystemActionEventDataRequired checks if the required fields are not zero-ed
func AssertSystemActionEventDataRequired(obj SystemActionEventData) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"type": obj.Type,
		"manufacturer": obj.Manufacturer,
		"domain": obj.Domain,
		"introducedAt": obj.IntroducedAt,
		"resolution": obj.Resolution,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSystemActionEventDataResolutionRequired(obj.Resolution); err != nil {
		return err
	}
	return nil
}

// AssertSystemActionEventDataConstraints checks if the values respects the defined constraints
func AssertSystemActionEventDataConstraints(obj SystemActionEventData) error {
	if err := AssertSystemActionEventDataResolutionConstraints(obj.Resolution); err != nil {
		return err
	}
	return nil
}
